# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesnap < Formula
  desc "Improved kubernetes context management tool"
  homepage "https://github.com/hunsy9/homebrew-kubesnap"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.3/kubesnap_darwin_x86_64.tar.gz"
      sha256 "f234560123998d73fd7c952adaae22157dd622c8c31c46b4a5c2a81b943ce547"

      def install
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.3/kubesnap_darwin_arm64.tar.gz"
      sha256 "09c0aa89f02128da410e48a21070d35245ae129f77bfc0fe07d3aa1d21aafd06"

      def install
        bin.install "ks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.3/kubesnap_linux_x86_64.tar.gz"
      sha256 "9d2b31d25cf11a91993421f06453792212e38996acfec7d1505244958dcff0c0"
      def install
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.3/kubesnap_linux_arm64.tar.gz"
      sha256 "1a0674ac4001396039e3d9e2a584c36375ca5ca81e2f77e9a5507589e3127bf6"
      def install
        bin.install "ks"
      end
    end
  end
end
