# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesnap < Formula
  desc "Improved kubernetes context management tool"
  homepage "https://github.com/hunsy9/homebrew-kubesnap"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.5/kubesnap_darwin_x86_64.tar.gz"
      sha256 "0f2ec4cd2069c2b85b10a079c04d80458f5817d56047da1a00ca9f1109f8d4db"

      def install
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.5/kubesnap_darwin_arm64.tar.gz"
      sha256 "c8deadd858efa5d681c08e94d941ac863ada46ba855d361ce9acbf2c69d9ba89"

      def install
        bin.install "ks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.5/kubesnap_linux_x86_64.tar.gz"
      sha256 "ceb38edcb945af7c53f5b14778ee1760d5e6ee87a9ed7016104dd0fa73bf1bda"
      def install
        bin.install "ks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hunsy9/kubesnap/releases/download/0.1.5/kubesnap_linux_arm64.tar.gz"
      sha256 "5228caa2d2de7e3792ec85643245e0f4b8e4400ee0eef4ef5fa7bdb530f6f595"
      def install
        bin.install "ks"
      end
    end
  end
end
